[theme]
primaryColor="#5383f9"
backgroundColor="#59acfb"
secondaryBackgroundColor="#5383f9"
textColor="#ffffff"
<<<<<<< HEAD
font="monospace"
=======
font="monospace"
>>>>>>> 22d7182368d104c9f47d23e6a129b19fc9554230
